---
- name: Fail when my_mail is not defined
  debug:
    msg: >-
      'my_mail' is required. Add the following to the playbook run:
      -e "{\"my_mail\": $(op item get fxwpqrzpncksdezymgzp6i7fbm --fields label=email)}"'
  failed_when: my_mail is not defined

- name: Create the cert-manager k8s namespace
  community.kubernetes.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: cert-manager
    api_version: v1
    kind: Namespace
    state: present

# - name: Download the CRD cert manager resource yaml
#   get_url:
#     url: https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.crds.yaml
#     dest: /tmp/cert-manager.crds.yaml
#     mode: '0777'

# - name: Ensure the CRD cert-manager resource is installed
#   community.kubernetes.k8s:
#     kubeconfig: /etc/rancher/k3s/k3s.yaml
#     src: /tmp/cert-manager.crds.yaml
#     namespace: cert-manager
#     state: present

- name: Ensure the cert-manager helm repo is available
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
    state: present

- name: Ensure the cert-manager is deployed
  community.kubernetes.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    release_state: present
    create_namespace: yes
    wait: yes
    values:
      installCRDs: true
      prometheus.enabled: true

- name: Make sure the cert-manager cluster-issuer is deployed
  community.kubernetes.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition: "{{ lookup('template', '../templates/cluster-issuer.yml') }}"
    state: present
    namespace: cert-manager
