---
- name: Ensure nfs service is running
  service:
    name: nfs-kernel-server
    state: started
    enabled: yes

- name: Ensure open-iscsi service is running
  service:
    name: open-iscsi
    state: started
    enabled: yes

- name: Ensure the longhorn helm repo is available
  community.kubernetes.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
    state: present

- name: install the longhorn helm chart
  community.kubernetes.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    release_state: present
    create_namespace: yes
    wait: yes
    wait_timeout: 1200s
    release_values: "{{ lookup('file', '../files/values.yml') | from_yaml }}"
  notify: check_kube_api

- name: update Longhorn UI service
  tags: [update-longhorn]
  kubernetes.core.k8s_json_patch:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    kind: Service
    namespace: longhorn-system
    name: longhorn-frontend
    patch:
      - op: add
        path: /metadata/annotations/metallb.universe.tf~1address-pool
        value: default-lb-pool
      - op: add
        path: /metadata/annotations/metallb.universe.tf~1ip-allocated-from-pool
        value: default-lb-pool
      - op: add
        path: /metadata/annotations/metallb.universe.tf~1loadBalancerIPs
        value: 10.1.10.254
      - op: replace
        path: /spec/type
        value: LoadBalancer

- name: recurring backup every day for default group - set facts
  set_fact:
    job:
      name: "default-backup"
      cron_schedule: "12 0/12 * * *"
      task: "backup"
      retain: 12
      groups:
        - default

- name: recurring backup every day for default group - debug
  debug:
    msg: "{{ lookup('template', 'recurring-job.yml.j2') }}"



- name: recurring backup every day for default group - set apply
  community.kubernetes.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition: "{{ lookup('template', 'recurring-job.yml.j2') | from_yaml }}"
    # validate:
    #   fail_on_error: yes

- name: recurring backup every day for important group - set facts
  set_fact:
    job:
      name: "important-backup"
      cron_schedule: "42 */6 * * *"
      task: "backup"
      retain: 8
      groups:
        - important

- name: recurring backup every day for important group - debug
  debug:
    msg: "{{ lookup('template', 'recurring-job.yml.j2') }}"

- name: recurring backup every day for important group - set apply
  community.kubernetes.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition: "{{ lookup('template', 'recurring-job.yml.j2') | from_yaml }}"
#    validate:
#      fail_on_error: yes
