---
- name: Ensure nfs service is running
  service:
    name: nfs-kernel-server
    state: started
    enabled: yes

- name: Ensure open-iscsi service is running
  service:
    name: open-iscsi
    state: started
    enabled: yes

- name: Ensure the longhorn helm repo is available
  community.kubernetes.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
    state: present

- name: install the longhorn helm chart
  community.kubernetes.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    release_state: present
    create_namespace: yes
    wait: yes
    timeout: 600s
    release_values: "{{ lookup('file', '../files/values.yml') | from_yaml }}"
