---
repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.11.2
    hooks:
      - id: gitleaks

  # - repo: https://github.com/ansible-community/ansible-lint
  #   rev: v6.5.1
  #   hooks:
  #     - id: ansible-lint
