---
- name: Ensure the k8s-at-home helm repo is available
  community.kubernetes.helm_repository:
    name: k8s-at-home
    repo_url: https://k8s-at-home.com/charts/
    state: present

- name: Create the namespace home-automation
  community.kubernetes.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: home-automation
    api_version: v1
    kind: Namespace
    state: present

- name: Create the configmap to backup-config
  community.kubernetes.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition: "{{ lookup('file', '../files/toolscripts-cm.yml') | from_yaml }}"
    validate:
      fail_on_error: yes

- name: Ensure home-assistant is installed
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: home-assistant
    chart_ref: k8s-at-home/home-assistant
    release_namespace: hoass
    release_state: present
    create_namespace: yes
    wait: no
    release_values: "{{ lookup('file', '../files/hoass-values.yml') | from_yaml }}"
