---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml

controller:
  annotations:
    operator.1password.io/item-path: "vaults/2pywcio4vfcenxsetefzmjpb6q/items/cmbjsiyrr3ikghwieb5wjekqea"
    operator.1password.io/item-name: "appdaemon-token"


image:
  # -- image repository
  repository: acockburn/appdaemon
  # -- image tag
  tag: 4.4.2
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See [image docs](https://appdaemon.readthedocs.io/en/latest/DOCKER_TUTORIAL.html) for more details.
# @default -- See below
env:
  - name: TZ
    value: "Europe/Zurich"
  - name: LATITUDE
    value: 47.4245
  - name: LONGITUDE
    value: 9.3767
  - name: ELEVATION
    value: 675
  - name: HA_URL
    valueFrom:
      secretKeyRef:
        name: appdaemon-token
        key: hostname
  - name: DASH_URL
    value: http:// 127.0.0.1:5050
  - name: TOKEN
    valueFrom:
      secretKeyRef:
        name: appdaemon-token
        key: credential

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    annotations:
      metallb.universe.tf/address-pool: default-lb-pool
      metallb.universe.tf/ip-allocated-from-pool: default-lb-pool
      metallb.universe.tf/loadBalancerIPs: 10.1.10.250
    type: LoadBalancer
    ports:
      http:
        targetPort: 5050
        port: 80


ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /conf
