---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml

controller:
  annotations:
    operator.1password.io/item-path: "vaults/2pywcio4vfcenxsetefzmjpb6q/items/cmbjsiyrr3ikghwieb5wjekqea"
    operator.1password.io/item-name: "appdaemon-token"


image:
  # -- image repository
  repository: acockburn/appdaemon
  # -- image tag
  tag: 4.2.1
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See [image docs](https://appdaemon.readthedocs.io/en/latest/DOCKER_TUTORIAL.html) for more details.
# @default -- See below
env:
  - name: TZ
    value: "Europe/Zurich"
  # LATITUDE:
  # LONGITUDE:
  # ELEVATION:
  - name: HA_URL
    valueFrom:
      secretKeyRef:
        name: appdaemon-token
        key: hostname
  - name: DASH_URL
    value: http:// 127.0.0.1:5050
  - name: TOKEN
    valueFrom:
      secretKeyRef:
        name: appdaemon-token
        key: credential

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    type: NodePort
    ports:
      http:
        port: 5050
        nodePort: 30102

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /conf
