---
persistence:
  enabled: true
  type: pvc
  size: 5Gi

annotations:
  operator.1password.io/item-path: "vaults/2pywcio4vfcenxsetefzmjpb6q/items/3grf2gm2fw77xopkbjo4y7tsbe"
  operator.1password.io/item-name: "grafana-credentials"

sidecar:
  dashboards:
    enabled: true
    searchNamespace: monitoring
    label: grafana_dashboard
    labelValue: 1
  datasources:
    enabled: true
    searchNamespace: monitoring
    label: grafana_datasource
    labelValue: 1

admin:
  existingSecret: "grafana-credentials"
  userKey: user
  passwordKey: password

serviceMonitor:
  enabled: true

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required - foo

  hosts:
    - grafana.riccardopetraglia.me

  tls:
    - hosts:
        - grafana.riccardopetraglia.me
      secretName: grafana-tls
