---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: loki
  name: loki
  namespace: monitoring
spec:
  endpoints:
    - interval: 1m
      path: /metrics
      port: http-metrics
      scrapeTimeout: 30s
  selector:
    matchLabels:
      app: loki
