---
- name: Make sure the kube-api is available (wait up to 300s)
  ansible.builtin.wait_for:
    port: 6443
    timeout: 10
  listen: check_kube_api

- name: Make sure the kube-api is answering
  shell: "curl -X GET https://127.0.0.1:6443 --silent -k"
  register: res
  until: res.stdout.find("401") != -1
  retries: 5
  delay: 3
  listen: check_kube_api
