---
- name: Set the timezone
  ansible.builtin.command:
    "timedatectl set-timezone Europe/Zurich"

- name: Activating cgroup support
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: reboot

- name: Installing iptables
  apt:
    name: iptables
    state: present
    update-cache: true
  register: iptables_installation

- name: Flush iptables before changing to iptables-legacy
  iptables:
    flush: true
  when: iptables_installation.changed

- name: Changing to iptables-legacy
  alternatives:
    path: /usr/sbin/iptables-legacy
    name: iptables
  register: ip4_legacy
  when: iptables_installation.changed

- name: Changing to ip6tables-legacy
  alternatives:
    path: /usr/sbin/ip6tables-legacy
    name: ip6tables
  register: ip6_legacy
  when: iptables_installation.changed

- name: Flush Handlers
  meta: flush_handlers
