---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#
# initContainers:
#   copy-configmap:
#     image: busybox
#     imagePullPolicy: IfNotPresent
#     command:
#       - "sh"
#       - "-c"
#       - |
#         cp -vL /app/configuration.yaml /data
#     volumeMounts:
#       - name: zigbee2mqtt-settings
#         mountPath: /app/configuration.yaml
#         subPath: configuration.yaml
#       - name: config
#         mountPath: /data

image:
  # -- image repository
  repository: koenkk/zigbee2mqtt
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See [image docs](https://appdaemon.readthedocs.io/en/latest/DOCKER_TUTORIAL.html) for more details.
# @default -- See below
env:
  TZ: "Europe/Zurich"
  ZIGBEE2MQTT_DATA: /app/data

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    type: NodePort
    ports:
      http:
        port: 8080
        nodePort: 30101

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

securityContext:
  privileged: false
# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  # config:
  #   enabled: true
  #   mountPath: /data

  clientcrt:
    enabled: true

  clientkey:
    enabled: true

  cacrt:
    enabled: true

# -- zigbee2mqtt configuration settings.
# This will be copied into the container's persistent storage at first run only.
# Further configuration should be done in the application itself!
# See [project documentation](https://www.zigbee2mqtt.io/information/configuration.html) for more information.
# @default -- See values.yaml
config:
  # These will be applied ONLY on first run
  # Home Assistant integration (MQTT discovery)
  homeassistant: true

  # allow new devices to join
  # WARNING: Disable this after all devices have been paired! (default: false)
  # Note: this will be controllable in the UI
  permit_join: true

  # MQTT settings
  mqtt:
    # MQTT base topic for zigbee2mqtt MQTT messages
    base_topic: zigbee2mqtt
    # MQTT server URL
    server: "mqtts://mosquitto.hoass.svc.cluster.local:8883"
    # MQTT server authentication, uncomment if required:
    user: "{{ mqtt_username }}"
    password: "{{ mqtt_password }}"

    reject_unauthorized: false
    # client_id: zigbee2mqtt
    # Alternatively, credentials may be put into a separate file, managed through a secret:
    # password: '!secret password'
    ca: '/certs/ca.crt'
    key: '/certs/zigbee2mqtt.key'
    cert: '/certs/zigbee2mqtt.crt'

    # Optional: Include device information to mqtt messages (default: false)
    include_device_information: true

  # USB / Serial settings
  serial:
    port: tcp://{{ zigbee_coordinator }}:6638
    # Location of your zigbee device
    # port: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2400981-if00

    # Optional: adapter type, not needed unless you are experiencing problems (options: zstack, deconz)
    # adapter: deconz

  advanced:
    network_key: GENERATE
    log_output:
      - console
    log_level: info

    # Optional: ZigBee channel, changing requires re-pairing of all devices. (Note: use a ZLL channel: 11, 15, 20, or 25 to avoid Problems)
    # default: 11
    # channel: 11

    # Optional: Baudrate for serial port (default: 115200 for Z-Stack, 38400 for Deconz)
    # baudrate: 38400

    # Optional: RTS / CTS Hardware Flow Control for serial port (default: false)
    # rtscts: true

    # Optional: Add a last_seen attribute to MQTT messages, contains date/time of last Zigbee message
    # possible values are: disable (default), ISO_8601, ISO_8601_local, epoch (default: disable)
    last_seen: 'ISO_8601_local'

    # homeassistant:
    #   discovery_topic: 'homeassistant'
    #   status_topic: 'homeassistant/status'

    # Optional: Enables report feature (see information -> report for more details) (default: false)
    # report: true

    # Optional: Add an elapsed attribute to MQTT messages, contains milliseconds since the previous msg (default: false)
    # elapsed: true

  # Both of these need to be enabled for the webui
  frontend:
    port: 8080
  experimental:
    new_api: true

tls:
  enabled: true
