---
- name: Install and start k3s
  ansible.builtin.include_tasks: ../../../../shared/install_and_start_k3s.yml

- name: Wait for node-token
  tags:
    - always
    - register-node-token
  wait_for:
    path: "{{ k3s.server_location }}/server/node-token"

- name: Register node-token file access mode
  tags:
    - always
    - register-node-token
  stat:
    path: "{{ k3s.server_location }}/server/node-token"
  register: p

- name: Change file access node-token
  tags:
    - always
    - register-node-token
  file:
    path: "{{ k3s.server_location }}/server/node-token"
    mode: "g+rx,o+rx"

- name: Read node-token from main master
  tags:
    - always
    - register-node-token
  slurp:
    path: "{{ k3s.server_location }}/server/node-token"
  register: node_token

- name: Store Master node-token
  tags:
    - always
    - register-node-token
  set_fact:
    token: "{{ node_token.content | regex_replace('\n', '') }}"

- name: Restore node-token file access
  tags:
    - always
    - register-node-token
  file:
    path: "{{ k3s.server_location }}/server/node-token"
    mode: "{{ p.stat.mode }}"

- name: Create directory .kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="

- name: Copy config file to user home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=,o="

- name: Replace https://localhost:6443 by https://master-ip:6443
  command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ ansible_default_ipv4.address }}:6443
      --kubeconfig ~{{ ansible_user }}/.kube/config
  changed_when: true

- name: Copy config file to user home directory for lb ip
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config.lb
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=,o="

- name: Replace https://localhost:6443 by https://master-ip:6443
  command: >-
    k3s kubectl config set-cluster default
      --kubeconfig ~{{ ansible_user }}/.kube/config.lb
      --server=https://{{ hostvars[groups['main_master'][0]]['ansible_default_ipv4']['address'] }}:6443
      --kubeconfig ~{{ ansible_user }}/.kube/config
  changed_when: true

- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link

- name: debugging
  debug:
    msg: "{{ lookup('template', '../templates/kubeapi-ep.yml.j2') }}"

- name: Pause for 5 minutes to make sure everything is ready
  ansible.builtin.pause:
    minutes: 5

- name: Create the kubeapi-lb endpoint
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    namespace: kube-public
    definition: "{{ lookup('template', '../templates/kubeapi-ep.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes


- name: Make sure the kubeapi is reachable using a lb
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition: "{{ lookup('template', '../templates/kubeapi-lb.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
