---
- name: Ensure the nginx/stable helm repo is available
  community.kubernetes.helm_repository:
    name: nginx-stable
    repo_url: https://kubernetes.github.io/ingress-nginx
    state: present

- name: Ensure nginx is installed
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: ingress-nginx
    chart_ref: nginx-stable/ingress-nginx
    release_namespace: ingress-nginx
    release_state: present
    create_namespace: yes
    wait: yes
    wait_timeout: 600s
    release_values: "{{ lookup('templates', '../templates/nginx-values.yml.j2') | from_yaml }}"
  notify: check_kube_api
