---
- name: Upgrade all packages installed in the pi
  apt:
    upgrade: safe
    update_cache: yes
    install_recommends: no
    autoclean: yes

- name: Install basic packages
  apt:
    name:
      - vim
      - ntp
      - htop
      - emacs-nox
      - tcpdump
      - python3-pip
      - python3-yaml
      - git
      - dbus
      - mosh
    state: present
  notify: reboot
