---
- name: Ensure the k8s-at-home helm repo is available
  community.kubernetes.helm_repository:
    name: my_k8s-at-home
    repo_url: https://grhawk.github.io/charts/
    state: present

- name: Create the namespace hoass
  community.kubernetes.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: hoass
    api_version: v1
    kind: Namespace
    state: present

- name: Ensure to create the needed certs
  community.kubernetes.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    namespace: hoass
    definition: "{{ lookup('template', '../../../../shared/generate-secret-from-op.yml.j2') }}"
    validate:
      fail_on_error: yes
  with_items:
    - {"secret_name": "mosquitto-secrets", "item_id": "uwn2i4tcjaoz65fxy23shehoja"}
    - {"secret_name": "mosquitto-ca-crt", "item_id": "rpczvdrrosedxyvg4ufzjajxbe"}

- name: Ensure mosquitto is installed
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    update_repo_cache: true
    name: mosquitto
    chart_ref: my_k8s-at-home/mosquitto
    release_namespace: hoass
    release_state: present
    create_namespace: yes
    wait: no
    release_values: "{{ lookup('file', '../files/mosquitto-values.yml') | from_yaml }}"
