---
apiVersion: v1
kind: Service
metadata:
  name: hoass-ssh-service
  namespace: home-automation
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/name: home-assistant
  ports:
    - port: 2222
      targetPort: 2222
      nodePort: 30022
