---
apiVersion: v1
data:
  automatic_github_backup.sh: |+
    #!/usr/bin/env bash

    # Put the script in a git repo and it will try to backup the repo to github
    # at every run.

    #set -euox

    exec 3>&1
    exec 2>&1


    LOCAL_REPO=/config
    REMOTE_REPO=""
    USERNAME=""
    PASSWORD=""

    cd $LOCAL_REPO || exit 3

    log () {
        echo "$( date -Ins) -- $1" | sed -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g'  >&3
    }

    first_backup=''

    # Check if in a git repo
    if ! `git status &> /dev/null`; then
        log "Not in a git repository - git init"
        git init
        git branch -m main
        git add .
        first_backup=true
    fi

    log "Starting backup to github ${REMOTE_REPO} of ${PWD}"

    if `git diff --exit-code &> /dev/null` && [ -z $first_backup ] ; then
        log "Nothing to backup... exit"
        exit 0
    fi

    git config --global user.email "automatic-backup@github.com"
    git config --global user.name "Automatic Backup"

    git commit -a -m 'Automatic backup' > /dev/null
    git push -u https://$USERNAME:$PASSWORD@$REMOTE_REPO main > /dev/null

    cd $PWD || exit 3

    log "Backup finished."

kind: ConfigMap
metadata:
  name: toolscripts
  namespace: home-automation
